export const employees = [
    {
        id: 1,
        name: "Suganya Prabagarane",
        title: "Developer",
        salary: 4000,
        phone: "555-1234",
        email: "suganyaprabagarane@gmail.com",
        animal: "Panda",
        startDate: "2024-12-15",
        location: "India",
        department: "Web Developer",
        skills: ["JavaScript", "React", "Node.js", "PHP"],

    },
    {
        id: 2,
        name: "Prabagarane",
        title: "Product Manager",
        salary: 5000,
        phone: "555-5678",
        email: "prabagarane@gmail.com",
        animal: "Dog",
        startDate: "2020-03-10",
        location: "Finland",
        department: "Product",
        skills: ["Agile", "Scrum", "Roadmapping"],

    },
    {
        id: 3,
        name: "Sonia",
        title: "UI/UX Designer",
        salary: 5000,
        phone: "555-2345",
        email: "sonia@gmail.com",
        animal: "Cat",
        startDate: "2020-5-01",
        location: "Bangaladesh",
        department: "Design",
        skills: ["Figma", "Sketch", "User Research"],

    },
    {
        id: 4,
        name: "Fizza",
        title: "DevOps Engineer",
        salary: 5500,
        phone: "555-8765",
        email: "fizza@gmail.com",
        animal: "Rabbit",
        startDate: "2014-12-20",
        location: "Pakistan",
        department: "Engineering",
        skills: ["AWS", "Docker", "CI/CD"],

    },
    {
        id: 5,
        name: "Devesh",
        title: "Data Scientist",
        salary: 45000,
        phone: "555-1357",
        email: "devesh@gmail.com",
        animal: "Cat",
        startDate: "2014-8-01",
        location: "India",
        department: "Data",
        skills: ["Python", "Machine Learning", "SQL"],

    },
    {
        id: 6,
        name: "Pragadhish",
        title: "Marketing Specialist",
        salary: 5400,
        phone: "555-2468",
        email: "pragadhish@gmail.com",
        animal: "Seal",
        startDate: "2020-08-12",
        location: "Finland",
        department: "Marketing",
        skills: ["SEO", "Content Strategy", "Google Ads"],

    },
    {
        id: 7,
        name: "Margit Tennosar",
        title: "Developer",
        salary: 8000,
        phone: "555-3691",
        email: "margit@gmail.com",
        animal: "Fox",
        startDate: "2010-5-23",
        location: "Estonia",
        department: "Web Developer",
        skills: ["React", "Javascript", "TypeScript"],

    },
    {
        id: 8,
        name: "Santosh",
        title: "Backend Developer",
        salary: 7000,
        phone: "555-7410",
        email: "santosh@gmail.com",
        animal: "Llama",
        startDate: "2019-05-30",
        location: "Phoenix",
        department: "Web Developer",
        skills: ["PHP", "Laravel", "Docker"],

    },
    {
        id: 9,
        name: "Keerthana",
        title: "QA Engineer",
        salary: 5000,
        phone: "555-3691",
        email: "keerthana@gmail.com",
        animal: "Rabbit",
        startDate: "2024-12-23",
        location: "Denver",
        department: "Engineering",
        skills: ["Selenium", "Jest", "Manual Testing"],

    },
    {
        id: 10,
        name: "Praveen",
        title: "Finance Analyst",
        salary: 5000,
        phone: "555-9630",
        email: "praveen@gmail.com",
        animal: "Tiger",
        startDate: "2024-10-05",
        location: "Los Angeles",
        department: "Finance",
        skills: ["Excel", "Forecasting", "Financial Modeling"],

    }
]